apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: lzipant
  labels:
    app: mysql
spec:
  selector:
    app: mysql
  clusterIP: None
  ports:
    - name: mysql
      port: 3306
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-read
  namespace: lzipant
  labels:
    app: mysql
spec:
  ports:
    - name: mysql
      port: 3306
  selector:
    app: mysql
