apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: lzipant
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 3
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.23.0
        ports:
        - containerPort: 80
