apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: lzipant
  labels:
    app: nginx
spec:
  ports:
  - protocol: TCP
    port: 80
    nodePort: 30080
    targetPort: 80
  type: NodePort
  selector:
    app: nginx
