apiVersion: kubeadm.k8s.io/v1beta3
kind: InitConfiguration
nodeRegistration:
  kubeletExtraArgs:
    cgroup-driver: "systemd"
---
apiVersion: kubeadm.k8s.io/v1beta3
kind: ClusterConfiguration
kubernetesVersion: "v1.24.1"
clusterName: "example-cluster"
controllerManager:
  extraArgs:
apiServer:
  extraArgs:
    runtime-config: "api/all=true"
