apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: managed-nfs-storage
  namespace: lzipant
provisioner: fuseim.pri/ifs # must match deployement env PROVISIONER_NAME
reclaimPolicy: Delete